### ISSUE TITLE
[refactor] 코드 정리

### ISSUE THREAD

**Issue by kimwest00** [kimwest00/sessac-management#24]
- [ ] 중복되는 함수 interface로 전환
- [ ] 코드 개선
   - [ ] idol add event 중복코드 메소드로 분리(event 조회, idol idx 반환)
   - [x]  menuController 코드 개선
   - [x] #32
- [x] 디렉토리 구조 패키지명 interface->method로 변경
- [x] 출력문
  - [x] 출력문 문구 상수화 / Object화 
  - [x] 예외처리

**Comment by lgy159** [comment]
menuController 파일 함수 개선 필요, 출력문 상수화 및 중복코드 함수화
allPrint 함수도 간결화 가능할것으로 보임, 현재 0,1,2 index로 switch 걸었으나 수정 필요.
Management 간에 중복되는 코드 존재 -> Interface화?
현재 예외처리 안되있는 부분도 있고, 간단하게 print로만 출력하게 되어있음 -> throw나 catch를 하여 해당 입력 부분 다시 받게하든 해야 함.

**Comment by kimwest00** [comment]
- idol add event 중복코드 메소드로 분리(event 조회, idol idx 반환)
 -  같은 메소드로 합치는 방법도 고려
- printconsole 중간에 exit 명령어가 작동가능한지
- inteface화의 경우 위의 comment와 중복되어 생략

**Comment by lgy159** [comment]
allPrint -> 리스트를 이용하여 간소화 예정
